balloon_ui <- function(local_folder = FALSE) {
  pair <- function(...) div(class = "input-pair", ...)
  section <- function(number, title, ...) div(class = "settings-section",
    h3(span(class = "step", number), title), ...)
  fluidPage(
    tags$head(tags$title("GSEA Balloon Plot"),
      tags$script(src = "browser-downloads.js"),
      tags$meta(name = "viewport", content = "width=device-width, initial-scale=1"),
      tags$link(rel = "stylesheet", href = "balloon.css")),
    div(class = "app-shell",
      tags$header(class = "app-header",
        div(div(class = "eyebrow", "EXPRESSION ANALYSIS / VISUALISATION"),
          h1("GSEA Balloon Plot"),
          p(class = "app-version", paste("Version", balloon_version())),
          p("Bring your comparisons together. Explore shared genesets and export a publication-ready figure.")),
        actionButton("load_example", "Try an example", class = "btn-example")),
      div(class = "workspace",
        tags$aside(class = "settings-panel",
          section("01", "Input files",
            if (local_folder) radioButtons("input_source", NULL,
              c("Select files" = "upload", "Local folder" = "folder"), inline = TRUE),
            if (local_folder) conditionalPanel("input.input_source === 'upload'",
              fileInput("files", "GSEA result tables", multiple = TRUE,
                accept = c(".txt", ".tsv", ".csv"), buttonLabel = "Choose files", placeholder = "Select one or more files")) else
              fileInput("files", "GSEA result tables", multiple = TRUE,
                accept = c(".txt", ".tsv", ".csv"), buttonLabel = "Choose files", placeholder = "Select one or more files"),
            if (local_folder) conditionalPanel("input.input_source === 'folder'",
              textInput("folder_path", "Input folder", placeholder = "/path/to/GSEA_results"),
              textInput("file_pattern", "Filename pattern", value = "\\.txt$"),
              actionButton("scan_folder", "Find matching files", class = "btn-block"),
              p(class = "field-help", "Selects all matching files directly inside this folder.")),
            p(class = "field-help", "One result file per comparison. Required columns: pathway, NES, padj."),
            tags$details(tags$summary("Input format & columns"),
              selectInput("separator", "Delimiter", c("Tab" = "tab", "Comma (CSV)" = "comma", "Semicolon" = "semicolon")),
              textInput("geneset_column", "Geneset column", "pathway"),
              pair(textInput("nes_column", "NES column", "NES"), textInput("padj_column", "padj column", "padj")),
              selectInput("file_encoding", "Text encoding", c("UTF-8-BOM", "UTF-8", "CP932", "latin1")))),
          section("02", "Geneset selection",
            textInput("geneset_padj_cutoff", "Minimum padj across comparisons: cutoff", placeholder = "No cutoff (e.g. 0.05)"),
            textInput("top_n_genesets", "Top N genesets by minimum padj", placeholder = "All (e.g. 20)"),
            helpText("Blank disables each filter. Keep genesets with min(padj) <= cutoff, then select the N smallest minima. Ties use geneset names. Uses included comparisons only.")),
          section("03", "Colour & size",
            div(class = "mapping-label", span(class = "colour-dot"), "Colour = signed NES"),
            pair(textInput("nes_min", "Minimum", placeholder = "Auto"), textInput("nes_max", "Maximum", placeholder = "Auto")),
            div(class = "mapping-label", span(class = "size-dot"), "Circle size = -log10(padj)"),
            pair(textInput("padj_min", "Minimum", placeholder = "Auto"), textInput("padj_max", "Maximum", placeholder = "Auto")),
            p(class = "field-help", "Leave either endpoint blank for automatic limits. Smaller padj gives a larger circle."),
            pair(numericInput("circle_min", "Smallest circle (mm)", 0.1, min = 0, step = 0.1),
              numericInput("circle_max", "Largest circle (mm)", 3.3, min = 0, step = 0.1)),
            checkboxInput("highlight_padj", "Black outlines for significant circles (0.5 pt)", FALSE),
            conditionalPanel("input.highlight_padj",
              numericInput("highlight_padj_cutoff", "Circle padj cutoff (<=)", 0.05, min = 0, max = 1, step = 0.01),
              helpText("Applies to each circle's own raw padj, independently of the geneset filter.")),
            tags$details(tags$summary("Colours & labels"),
              textInput("colour_low", "Negative NES colour", "dodgerblue3"),
              textInput("colour_mid", "Zero NES colour", "gray95"),
              textInput("colour_high", "Positive NES colour", "darkorange3"),
              checkboxInput("show_nes_sign", "Show + / - / 0 inside circles", FALSE))),
          section("04", "Layout",
            textInput("plot_title", "Plot title", "Hallmark"),
            pair(div(checkboxInput("auto_width", "Auto width", TRUE),
                  conditionalPanel("!input.auto_width", numericInput("width_mm", "Width (mm)", 120, min = 1))),
              div(checkboxInput("auto_height", "Auto height", TRUE),
                  conditionalPanel("!input.auto_height", numericInput("height_mm", "Height (mm)", 180, min = 1)))),
            selectInput("geneset_order", "Geneset order", c("First selected file" = "first_file", "Alphabetical" = "alphabetical")),
            checkboxInput("cluster_genesets", "Cluster genesets", FALSE),
            checkboxInput("cluster_samples", "Cluster samples (comparisons)", FALSE),
            conditionalPanel("input.cluster_genesets || input.cluster_samples",
              selectInput("cluster_distance", "Clustering distance", c("Euclidean" = "euclidean", "Manhattan" = "manhattan", "Pearson (1 - r)" = "pearson")),
              selectInput("cluster_method", "Clustering linkage", c("Complete" = "complete", "Average" = "average", "Ward.D2 (Euclidean only)" = "ward.D2")),
              helpText("Uses raw signed NES profiles of the displayed genesets. Reorders selected axes; no dendrogram is drawn. Missing NES cannot be clustered.")),
            helpText("Geneset order and file Order apply when clustering that axis is off."),
            tags$details(tags$summary("Fonts, spacing & lines"),
              pair(numericInput("font_axis", "Axis labels (pt)", 6, min = 1), numericInput("font_title", "Title (pt)", 8, min = 1)),
              pair(numericInput("font_legend", "Legend text (pt)", 6, min = 1), numericInput("font_legend_title", "Legend title (pt)", 6, min = 1)),
              selectInput("font_family", "Font family", c("Sans serif" = "sans", "Serif" = "serif", "Monospace" = "mono")),
              pair(numericInput("cell_mm", "Cell spacing (mm)", 2.95, min = 0.1, step = 0.05),
                numericInput("aspect", "Row / column spacing", 1, min = 0.1, step = 0.1)),
              pair(numericInput("border_pt", "Panel border (pt)", 0.25, min = 0, step = 0.05),
                numericInput("ticks_pt", "Axis ticks (pt)", 0.25, min = 0, step = 0.05)),
              numericInput("grid_pt", "Grid lines (pt; 0 hides grid)", 0.25, min = 0, step = 0.05),
              textInput("padj_floor", "Floor for zero / tiny padj", "1e-300")),
            tags$details(tags$summary("Export settings"),
              textInput("output_prefix", "Output filename prefix", "balloon_Hallmark"),
              numericInput("png_dpi", "PNG resolution (dpi)", 300, min = 72, step = 50))),
          div(class = "update-bar", actionButton("update_plot", "Update plot", class = "btn-primary btn-block"),
            p("Only genesets present in every included file are plotted."))
        ),
        tags$main(class = "results-panel",
          div(class = "card input-card", div(class = "card-heading", h2("Comparisons"), textOutput("file_count", inline = TRUE)),
            p(class = "subtle", "Edit labels, choose comparisons, and set their left-to-right order."),
            uiOutput("file_editor")),
          uiOutput("feedback"),
          uiOutput("metrics"),
          div(class = "card plot-card",
            div(class = "card-heading", h2("Plot preview"), uiOutput("plot_state", inline = TRUE)),
            uiOutput("preview_body"),
            uiOutput("resolved_ranges"),
            div(class = "download-bar", uiOutput("download_controls"),
          div(id = "balloon-file-ready", role = "status", `aria-live` = "polite"))),
          tags$details(class = "card summary-card", tags$summary("Data checks & input summary"),
            p(class = "subtle", "Shared means present in every included file, before the optional geneset filters. Displayed counts are shown above."),
            div(class = "table-scroll", tableOutput("input_summary"))),
          tags$footer("Colour: NES direction ", span("·"), " Size: -log10(padj) ", span("·"),
            " PDF dimensions and line widths are preserved on export.")
        )
      )
    )
  )
}
